// Auto-generated by esm-styles - provides global $theme, $device, etc.
// Add to tsconfig.json: "include": ["path/to/source/globals.d.ts"]

declare const $device: typeof import('./$device.mjs').default
declare const $theme: typeof import('./$theme.mjs').default
