/**
 * ESM Styles - TypeScript definitions for style objects
 *
 * Provides type safety and autocompletion for CSS properties
 * while maintaining the flexible, nested syntax of esm-styles.
 */

import type { Properties, Pseudos } from 'csstype'

// ============================================
// CSS Variable Support
// ============================================

/**
 * CSS variable reference object (as generated by $theme/$device modules)
 */
export interface CSSVariableRef {
  var: string
  name?: string
  [key: string]: string | undefined // theme values like 'light', 'dark'
}

/**
 * Value that can be used for any CSS property
 */
export type CSSValue = string | number | CSSVariableRef

/**
 * CSS Properties with support for CSS variable references
 * Using csstype's Properties as base with extended value types
 */
export type CSSProperties = {
  [K in keyof Properties]?: Properties[K] | CSSValue
}

// ============================================
// Pseudo-classes and Pseudo-elements
// ============================================

/**
 * Common pseudo-class and pseudo-element keys for better autocompletion
 */
export type CommonPseudos =
  | ':hover'
  | ':active'
  | ':focus'
  | ':focus-visible'
  | ':focus-within'
  | ':visited'
  | ':disabled'
  | ':enabled'
  | ':checked'
  | ':first-child'
  | ':last-child'
  | ':nth-child'
  | ':not'
  | ':has'
  | '::before'
  | '::after'
  | '::placeholder'
  | '::selection'
  | '::first-line'
  | '::first-letter'

// ============================================
// Style Object (recursive)
// ============================================

/**
 * Complete style object type.
 *
 * Due to TypeScript limitations with index signatures,
 * we use a permissive approach that still provides
 * autocompletion for CSS properties while allowing
 * nested selectors.
 *
 * The tradeoff: typos in CSS property names won't be caught,
 * but you get full autocompletion when typing.
 */
export type StyleObject = CSSProperties & {
  // Pseudo-classes and pseudo-elements
  [K in CommonPseudos]?: StyleObject
} & {
  // Allow any string key for:
  // - Media queries (@media, @dark, @mobile, etc.)
  // - Nested selectors (button, __icon, _active, etc.)
  // - Other pseudo-classes not in CommonPseudos
  [selector: string]: StyleObject | CSSValue | string | undefined
}

/**
 * Root-level stylesheet with named selectors
 */
export type StyleSheet = {
  [selector: string]: StyleObject
}

// ============================================
// Strict Types (opt-in for stricter checking)
// ============================================

/**
 * Strict CSS properties without nested selectors.
 * Use this for leaf-level style objects where you want
 * full type checking and no nested selectors are needed.
 */
export type StrictCSSProperties = {
  [K in keyof Properties]?: Properties[K] | CSSValue
}

/**
 * Strict style object with explicit nested selector type.
 * Provides better type checking at the cost of more verbose syntax.
 */
export interface StrictStyleObject extends StrictCSSProperties {
  // Explicitly typed pseudo-classes
  ':hover'?: StrictStyleObject
  ':active'?: StrictStyleObject
  ':focus'?: StrictStyleObject
  ':focus-visible'?: StrictStyleObject
  ':disabled'?: StrictStyleObject
  '::before'?: StrictStyleObject
  '::after'?: StrictStyleObject
  '::placeholder'?: StrictStyleObject
}

// ============================================
// Helper Functions
// ============================================

/**
 * Define a typed stylesheet with autocompletion.
 *
 * @example
 * ```ts
 * import { defineStyles } from 'esm-styles'
 * import $theme from './$theme'
 *
 * export default defineStyles({
 *   button: {
 *     backgroundColor: $theme.paper.bright,
 *     padding: '12px 24px',
 *
 *     ':hover': {
 *       opacity: 0.9,
 *     },
 *
 *     '@dark': {
 *       backgroundColor: $theme.paper.tinted,
 *     },
 *
 *     __icon: {
 *       width: '20px',
 *     },
 *   },
 * })
 * ```
 */
export function defineStyles<T extends StyleSheet>(styles: T): T {
  return styles
}

/**
 * Define a component style for named export.
 * Use this in component files that are imported into floor modules.
 *
 * @example
 * ```ts
 * // button.styles.ts
 * import { defineComponent } from 'esm-styles'
 * import $theme from './$theme'
 *
 * export const button = defineComponent({
 *   padding: '12px 24px',
 *   backgroundColor: $theme.paper.bright,
 *
 *   ':hover': { opacity: 0.9 },
 *   '@dark': { backgroundColor: $theme.paper.tinted },
 *
 *   primary: { backgroundColor: 'blue' },
 *   __icon: { width: '20px' },
 * })
 * ```
 *
 * ```ts
 * // components.styles.ts (floor module)
 * import { defineStyles } from 'esm-styles'
 * import { button } from './button.styles'
 *
 * export default defineStyles({ button })
 * ```
 */
export function defineComponent<T extends StyleObject>(styles: T): T {
  return styles
}

/**
 * Define a reusable style mixin (for spreading into other styles).
 *
 * @example
 * ```ts
 * import { defineMixin } from 'esm-styles'
 *
 * export const flexCenter = defineMixin({
 *   display: 'flex',
 *   alignItems: 'center',
 *   justifyContent: 'center',
 * })
 *
 * // Usage:
 * export const card = defineComponent({
 *   ...flexCenter,
 *   padding: '24px',
 * })
 * ```
 */
export function defineMixin<T extends StyleObject>(mixin: T): T {
  return mixin
}

/**
 * Define strict CSS properties (no nesting, full type checking).
 * Use for simple style objects where you want maximum type safety.
 *
 * @example
 * ```ts
 * const buttonBase = defineStrict({
 *   display: 'inline-flex',
 *   padding: '12px 24px',
 *   // backgroundColr: 'red',  // ❌ TypeScript error!
 * })
 * ```
 */
export function defineStrict<T extends StrictCSSProperties>(styles: T): T {
  return styles
}

// ============================================
// Theme Token Types (for $theme generation)
// ============================================

/**
 * Leaf token with CSS variable reference
 */
export interface ThemeToken extends CSSVariableRef {
  var: string
  name: string
}

/**
 * Nested theme tokens structure
 */
export type ThemeTokens = {
  [key: string]: ThemeToken | ThemeTokens
}

// ============================================
// Re-export csstype for advanced users
// ============================================

export type { Properties, Pseudos } from 'csstype'
